name: Publish

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x
      - name: Get Version
        uses: kzrnm/get-net-sdk-project-versions-action@v1.3.0
        id: get-version
        with:
          proj-path: src/FEntwumS.FSM/FEntwumS.FSM.csproj
      - name: Build
        run: dotnet build src/FEntwumS.FSM/FEntwumS.FSM.csproj -c Release -o publish

      - name: Compress
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: ../FEntwumS.FSM_${{steps.get-version.outputs.version}}_all.zip
          directory: ./publish
      - name: Debug
        run: ls && ls -lshaR publish
      - uses: ncipollo/release-action@v1.14.0
        with:
          artifacts: "FEntwumS.FSM_${{steps.get-version.outputs.version}}_all.zip,./publish/compatibility.txt"
          tag: ${{steps.get-version.outputs.version}}
          allowUpdates: true
          replacesArtifacts: true
          generateReleaseNotes: true
          omitBodyDuringUpdate: true